DROP SCHEMA IF EXISTS sc2_lab CASCADE;
CREATE SCHEMA sc2_lab;
SET search_path TO sc2_lab, public;

CREATE TABLE lab_sessions (
    session_id   integer PRIMARY KEY,
    session_name text    NOT NULL,
    available_workstations integer NOT NULL CHECK (available_workstations >= 0)   
);

CREATE TABLE reservations (
    reservation_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    session_id   integer NOT NULL REFERENCES lab_sessions(session_id),
    lecturer text    NOT NULL,
    workstations   integer NOT NULL CHECK (workstations > 0),
    status  text    NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

INSERT INTO lab_sessions (session_id, session_name, available_workstations)
VALUES (1, 'Monday 08:00 - Networking', 30),
       (2, 'Tuesday 10:00 - Databases', 5),
       (3, 'Wednesday 14:00 - Programming', 0);

SELECT * FROM lab_sessions ORDER BY session_id;


DO $$
DECLARE
    r record;
BEGIN
    FOR r IN SELECT session_name, available_workstations FROM sc2_lab.lab_sessions ORDER BY session_id LOOP
        IF r.available_workstations = 0 THEN
            RAISE NOTICE 'Session "%" is full', r.session_name;
        ELSIF r.available_workstations <= 5 THEN
            RAISE NOTICE 'Session "%" is nearly full: % workstations left', r.session_name, r.available_workstations;
        ELSE
            RAISE NOTICE 'Session "%" has enough workstations: %', r.session_name, r.available_workstations;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


DO $$
DECLARE
    v_n integer := 1;
BEGIN
    WHILE v_n <= 3 LOOP
        RAISE NOTICE 'Session preparation reminder %', v_n;
        v_n := v_n + 1;
    END LOOP;

    FOR v_i IN 1..3 LOOP
        RAISE NOTICE 'Workstation check %', v_i;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE PROCEDURE sc2_lab.reserve_workstations(
    p_session_id   integer,
    p_lecturer text,
    p_workstations   integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_new_id    integer;
BEGIN
  
    IF p_workstations <= 0 THEN
        RAISE EXCEPTION 'Number of workstations must be positive'
            USING ERRCODE = '22023';          
    END IF;
    IF p_lecturer IS NULL OR btrim(p_lecturer) = '' THEN
        RAISE EXCEPTION 'Lecturer must not be blank'
            USING ERRCODE = '22023';
    END IF;

    
    SELECT available_workstations INTO v_available
    FROM sc2_lab.lab_sessions
    WHERE session_id = p_session_id
    FOR UPDATE;

    
    IF NOT FOUND THEN
        RAISE NOTICE 'Session % does not exist', p_session_id;
        RETURN;
    ELSIF v_available < p_workstations THEN
        RAISE NOTICE 'Insufficient workstations: only % available', v_available;
        RETURN;
    END IF;

    UPDATE sc2_lab.lab_sessions
    SET available_workstations = available_workstations - p_workstations
    WHERE session_id = p_session_id;

    INSERT INTO sc2_lab.reservations (session_id, lecturer, workstations, status)
    VALUES (p_session_id, p_lecturer, p_workstations, 'ACTIVE')
    RETURNING reservation_id INTO v_new_id;

    RAISE NOTICE 'Reservation % recorded for lecturer %', v_new_id, p_lecturer;
END;
$$;


CALL sc2_lab.reserve_workstations(1, 'Dr Banda', 20);
CALL sc2_lab.reserve_workstations(2, 'Mr Phiri', 3);
CALL sc2_lab.reserve_workstations(2, 'Ms Mumba', 10);   

SELECT session_id, session_name, available_workstations
FROM sc2_lab.lab_sessions ORDER BY session_id;

SELECT reservation_id, session_id, lecturer, workstations, status
FROM sc2_lab.reservations ORDER BY reservation_id;


CREATE OR REPLACE PROCEDURE sc2_lab.cancel_reservation(p_reservation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item_id integer;
    v_qty     integer;
BEGIN
    SELECT session_id, workstations
    INTO v_item_id, v_qty
    FROM sc2_lab.reservations
    WHERE reservation_id = p_reservation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active reservation with ID %', p_reservation_id;
        RETURN;
    END IF;

    UPDATE sc2_lab.reservations
    SET status = 'CANCELLED'
    WHERE reservation_id = p_reservation_id;

    UPDATE sc2_lab.lab_sessions
    SET available_workstations = available_workstations + v_qty
    WHERE session_id = v_item_id;

    RAISE NOTICE 'Reservation % cancelled; % workstations released', p_reservation_id, v_qty;
END;
$$;

CALL sc2_lab.cancel_reservation(1);   
CALL sc2_lab.cancel_reservation(1);   

SELECT * FROM sc2_lab.lab_sessions ORDER BY session_id;
SELECT reservation_id, status FROM sc2_lab.reservations ORDER BY reservation_id;


CREATE OR REPLACE PROCEDURE sc2_lab.show_low_sessions(p_threshold integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR (p_limit integer) FOR
        SELECT session_name, available_workstations
        FROM sc2_lab.lab_sessions
        WHERE available_workstations <= p_limit
        ORDER BY session_id;
BEGIN
    OPEN c_low(p_threshold);
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;          
        RAISE NOTICE 'Few workstations left: "%" (% remaining)', v_item.session_name, v_item.available_workstations;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL sc2_lab.show_low_sessions(5);


DO $$
BEGIN
    CALL sc2_lab.reserve_workstations(3, 'Dr Zulu', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

SELECT COUNT(*) AS number_of_reservations
FROM sc2_lab.reservations;         
SELECT session_id, session_name, available_workstations
FROM sc2_lab.lab_sessions ORDER BY session_id;

SELECT reservation_id, session_id, lecturer, workstations, status
FROM sc2_lab.reservations ORDER BY reservation_id;
