DROP SCHEMA IF EXISTS sc4_clinic CASCADE;
CREATE SCHEMA sc4_clinic;
SET search_path TO sc4_clinic, public;

CREATE TABLE medicines (
    medicine_id   integer PRIMARY KEY,
    medicine_name text    NOT NULL,
    stock_quantity integer NOT NULL CHECK (stock_quantity >= 0)   
);

CREATE TABLE dispensing_records (
    record_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id   integer NOT NULL REFERENCES medicines(medicine_id),
    student_number text    NOT NULL,
    quantity   integer NOT NULL CHECK (quantity > 0),
    status  text    NOT NULL CHECK (status IN ('DISPENSED', 'REVERSED'))
);

INSERT INTO medicines (medicine_id, medicine_name, stock_quantity)
VALUES (1, 'Paracetamol 500mg', 100),
       (2, 'Amoxicillin 250mg', 15),
       (3, 'ORS Sachets', 0);

SELECT * FROM medicines ORDER BY medicine_id;


DO $$
DECLARE
    r record;
BEGIN
    FOR r IN SELECT medicine_name, stock_quantity FROM sc4_clinic.medicines ORDER BY medicine_id LOOP
        IF r.stock_quantity = 0 THEN
            RAISE NOTICE 'Medicine "%" is out of stock', r.medicine_name;
        ELSIF r.stock_quantity <= 20 THEN
            RAISE NOTICE 'Medicine "%" is low on stock: % left', r.medicine_name, r.stock_quantity;
        ELSE
            RAISE NOTICE 'Medicine "%" is sufficiently stocked: %', r.medicine_name, r.stock_quantity;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


DO $$
DECLARE
    v_n integer := 1;
BEGIN
    WHILE v_n <= 3 LOOP
        RAISE NOTICE 'Stock review day %', v_n;
        v_n := v_n + 1;
    END LOOP;

    FOR v_i IN 1..3 LOOP
        RAISE NOTICE 'Shelf inspection %', v_i;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE PROCEDURE sc4_clinic.dispense_medicine(
    p_medicine_id   integer,
    p_student_number text,
    p_quantity   integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_new_id    integer;
BEGIN
  
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
            USING ERRCODE = '22023';          
    END IF;
    IF p_student_number IS NULL OR btrim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student must not be blank'
            USING ERRCODE = '22023';
    END IF;

   
    SELECT stock_quantity INTO v_available
    FROM sc4_clinic.medicines
    WHERE medicine_id = p_medicine_id
    FOR UPDATE;

    
    IF NOT FOUND THEN
        RAISE NOTICE 'Medicine % does not exist', p_medicine_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_available;
        RETURN;
    END IF;

    UPDATE sc4_clinic.medicines
    SET stock_quantity = stock_quantity - p_quantity
    WHERE medicine_id = p_medicine_id;

    INSERT INTO sc4_clinic.dispensing_records (medicine_id, student_number, quantity, status)
    VALUES (p_medicine_id, p_student_number, p_quantity, 'DISPENSED')
    RETURNING record_id INTO v_new_id;

    RAISE NOTICE 'Dispensing record % recorded for student %', v_new_id, p_student_number;
END;
$$;


CALL sc4_clinic.dispense_medicine(1, 'STU001', 30);
CALL sc4_clinic.dispense_medicine(2, 'STU002', 5);
CALL sc4_clinic.dispense_medicine(2, 'STU003', 50);  
SELECT medicine_id, medicine_name, stock_quantity
FROM sc4_clinic.medicines ORDER BY medicine_id;

SELECT record_id, medicine_id, student_number, quantity, status
FROM sc4_clinic.dispensing_records ORDER BY record_id;


CREATE OR REPLACE PROCEDURE sc4_clinic.reverse_dispensing(p_record_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item_id integer;
    v_qty     integer;
BEGIN
    SELECT medicine_id, quantity
    INTO v_item_id, v_qty
    FROM sc4_clinic.dispensing_records
    WHERE record_id = p_record_id AND status = 'DISPENSED'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No dispensed record that can be reversed with ID %', p_record_id;
        RETURN;
    END IF;

    UPDATE sc4_clinic.dispensing_records
    SET status = 'REVERSED'
    WHERE record_id = p_record_id;

    UPDATE sc4_clinic.medicines
    SET stock_quantity = stock_quantity + v_qty
    WHERE medicine_id = v_item_id;

    RAISE NOTICE 'Dispensing record % reversed; % units restored to stock', p_record_id, v_qty;
END;
$$;

CALL sc4_clinic.reverse_dispensing(1);   
CALL sc4_clinic.reverse_dispensing(1);

SELECT * FROM sc4_clinic.medicines ORDER BY medicine_id;
SELECT record_id, status FROM sc4_clinic.dispensing_records ORDER BY record_id;


CREATE OR REPLACE PROCEDURE sc4_clinic.show_low_medicines(p_threshold integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR (p_limit integer) FOR
        SELECT medicine_name, stock_quantity
        FROM sc4_clinic.medicines
        WHERE stock_quantity <= p_limit
        ORDER BY medicine_id;
BEGIN
    OPEN c_low(p_threshold);
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;          
        RAISE NOTICE 'Below threshold: "%" (% in stock)', v_item.medicine_name, v_item.stock_quantity;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL sc4_clinic.show_low_medicines(20);


DO $$
BEGIN
    CALL sc4_clinic.dispense_medicine(3, 'STU004', -5);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

SELECT COUNT(*) AS number_of_dispensing_records
FROM sc4_clinic.dispensing_records;         
SELECT medicine_id, medicine_name, stock_quantity
FROM sc4_clinic.medicines ORDER BY medicine_id;

SELECT record_id, medicine_id, student_number, quantity, status
FROM sc4_clinic.dispensing_records ORDER BY record_id;
