DROP SCHEMA IF EXISTS  sc5_workshop CASCADE;
CREATE SCHEMA sc5_workshop;
SET search_path TO sc5_workshop, public;

CREATE TABLE tools (
    tool_id   integer PRIMARY KEY,
    tool_name text    NOT NULL,
    available_quantity integer NOT NULL CHECK (available_quantity >= 0)  
);

CREATE TABLE tool_loans (
    loan_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    tool_id   integer NOT NULL REFERENCES tools(tool_id),
    student_number text    NOT NULL,
    quantity   integer NOT NULL CHECK (quantity > 0),
    status  text    NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED'))
);

INSERT INTO tools (tool_id, tool_name, available_quantity)
VALUES (1, 'Multimeter', 10),
       (2, 'Soldering Iron', 3),
       (3, 'Vernier Caliper', 0);

SELECT * FROM tools ORDER BY tool_id;


DO $$
DECLARE
    r record;
BEGIN
    FOR r IN SELECT tool_name, available_quantity FROM sc5_workshop.tools ORDER BY tool_id LOOP
        IF r.available_quantity = 0 THEN
            RAISE NOTICE 'Tool "%" is unavailable', r.tool_name;
        ELSIF r.available_quantity <= 3 THEN
            RAISE NOTICE 'Tool "%" is low on stock: % left', r.tool_name, r.available_quantity;
        ELSE
            RAISE NOTICE 'Tool "%" is readily available: %', r.tool_name, r.available_quantity;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


DO $$
DECLARE
    v_n integer := 1;
BEGIN
    WHILE v_n <= 3 LOOP
        RAISE NOTICE 'Workshop safety reminder %', v_n;
        v_n := v_n + 1;
    END LOOP;

    FOR v_i IN 1..3 LOOP
        RAISE NOTICE 'Tool inspection %', v_i;
    END LOOP;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE PROCEDURE sc5_workshop.issue_tool(
    p_tool_id   integer,
    p_student_number text,
    p_quantity   integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_new_id    integer;
BEGIN
    
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
            USING ERRCODE = '22023';          
    END IF;
    IF p_student_number IS NULL OR btrim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student must not be blank'
            USING ERRCODE = '22023';
    END IF;

   
    SELECT available_quantity INTO v_available
    FROM sc5_workshop.tools
    WHERE tool_id = p_tool_id
    FOR UPDATE;

    
    IF NOT FOUND THEN
        RAISE NOTICE 'Tool % does not exist', p_tool_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_available;
        RETURN;
    END IF;

    UPDATE sc5_workshop.tools
    SET available_quantity = available_quantity - p_quantity
    WHERE tool_id = p_tool_id;

    INSERT INTO sc5_workshop.tool_loans (tool_id, student_number, quantity, status)
    VALUES (p_tool_id, p_student_number, p_quantity, 'ACTIVE')
    RETURNING loan_id INTO v_new_id;

    RAISE NOTICE 'Tool loan % recorded for student %', v_new_id, p_student_number;
END;
$$;


CALL sc5_workshop.issue_tool(1, 'STU001', 4);
CALL sc5_workshop.issue_tool(2, 'STU002', 1);
CALL sc5_workshop.issue_tool(2, 'STU003', 5);  

SELECT tool_id, tool_name, available_quantity
FROM sc5_workshop.tools ORDER BY tool_id;

SELECT loan_id, tool_id, student_number, quantity, status
FROM sc5_workshop.tool_loans ORDER BY loan_id;


CREATE OR REPLACE PROCEDURE sc5_workshop.return_tool(p_loan_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item_id integer;
    v_qty     integer;
BEGIN
    SELECT tool_id, quantity
    INTO v_item_id, v_qty
    FROM sc5_workshop.tool_loans
    WHERE loan_id = p_loan_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active tool loan with ID %', p_loan_id;
        RETURN;
    END IF;

    UPDATE sc5_workshop.tool_loans
    SET status = 'RETURNED'
    WHERE loan_id = p_loan_id;

    UPDATE sc5_workshop.tools
    SET available_quantity = available_quantity + v_qty
    WHERE tool_id = v_item_id;

    RAISE NOTICE 'Tool loan % returned; % tools added back to stock', p_loan_id, v_qty;
END;
$$;

CALL sc5_workshop.return_tool(1);  
CALL sc5_workshop.return_tool(1);   

SELECT * FROM sc5_workshop.tools ORDER BY tool_id;
SELECT loan_id, status FROM sc5_workshop.tool_loans ORDER BY loan_id;


CREATE OR REPLACE PROCEDURE sc5_workshop.show_low_tools(p_threshold integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR (p_limit integer) FOR
        SELECT tool_name, available_quantity
        FROM sc5_workshop.tools
        WHERE available_quantity <= p_limit
        ORDER BY tool_id;
BEGIN
    OPEN c_low(p_threshold);
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;          
        RAISE NOTICE 'Low availability: "%" (% left)', v_item.tool_name, v_item.available_quantity;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL sc5_workshop.show_low_tools(3);


DO $$
BEGIN
    CALL sc5_workshop.issue_tool(3, 'STU004', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

SELECT COUNT(*) AS number_of_tool_loans
FROM sc5_workshop.tool_loans;
SELECT tool_id, tool_name, available_quantity
FROM sc5_workshop.tools ORDER BY tool_id;

SELECT loan_id, tool_id, student_number, quantity, status
FROM sc5_workshop.tool_loans ORDER BY loan_id;
